#################################################################################
## ALGORITHM
##################################################################################
# Learning rate for actor
actor_lr: 0.0001

# Learning rate for critic
critic_lr: 0.0002

# Learning rate for gain
gain_lr: 0.2

# Learning rate for inference
inference_lr: 0.0002

# Weight for entropy
entropy_weight: 0.01

# Number of latent variables
n_latent: 10

# Weight of KL loss in inference optimization
kl_weight: 0.01

# Number of samples to use for each train iteration
batch_size: 256

# Max timestep to train agents
max_timestep: 300000

# Number of neurons for hidden network
n_hidden: 256

# Training mode for inference [batch, sequential]
inference_train_mode: "batch"


#################################################################################
## ENV
##################################################################################
# OpenAI gym environment name
env_name: "Acrobot-v1"
